easy = ["HAMMER", "TITLE", "BALLOON", "WEEK", "CROSS", "BUBBLE", "SUCCESS", "STREET", "SUSHI", "QUEEN"]

medium = ["PHOTOGRAPH", "COWBOY", "DIFFICULT", "LONDON", "PASSWORD", "GEOMETRY", "CHALKBOARD", "ELECTRICITY", "BATTLESHIP", "AMERICA"]

hard = ["GIBRALTAR", "TERRITORY", "SAMURAI", "FLYBY", "PNEUMONIA", "SACRILEGIOUS", "XENOLITH", "LOGORRHEA", "ANACHRONISTIC", "GRANDILOQUENT"]

impossible = ["ANTIDISESTABLISHMENTARIANISM", "SUPERCALIFRAGILISTICEXPIALIDOCIOUS", "INCOMPREHENSIBILITIES", "OUAGADOUGOU", "PULCHRITUDINOUS", "PSYCHOTOMIMETIC", "TRICHOTILLOMANIA", "MYRMECOPHILOUS", "XENOTRANSPLANTATION", "EMBOURGEOISEMENT"]

create = []